In [1]:
import numpy as np
np.random.seed(123)

In [2]:
# 100 throws of dice
# If dice = 1,2 go down by 1 step
# If dice = 3,4,5 go up by 1 step
# if dice = 6, then throw dice again and go up by value on dice
# You can go below step 0 
# And you have 0.1% chance of falling, which mean you will start from step 0
# You have to reach step 60, what is the chace u will win this bet

In [3]:
# We can stimulate 100 throws for many times and get the distribution for each time and based on distribution 
# we can get the chance/probability

In [4]:
random_walk = []
for i in range(500):
    step = [0]
    for i in range(100):
        dice = np.random.randint(1,7)
        if dice <= 2:
            step.append(max(0,step[-1]-1))
        elif dice > 2 and dice < 6:
            step.append(step[-1]+1)
        else:
            step.append(step[-1]+np.random.randint(1,7))
    random_walk.append(step)

In [5]:
#Random Walk Has path for 100 dice rows in each of 250 simulation
random_walk = np.array(random_walk)
print(random_walk.shape)
print(random_walk)

(500, 101)
[[ 0  3  4 ... 58 59 60]
 [ 0  4  3 ... 70 71 73]
 [ 0  2  1 ... 85 84 83]
 ...
 [ 0  1  2 ... 95 94 95]
 [ 0  3  2 ... 80 81 80]
 [ 0  1  2 ... 60 59 60]]


In [6]:
#  Now if we take the transpose of random walk , then we will have for the step number for 250 trials
random_walk_transpose = np.transpose(random_walk)
print(random_walk_transpose)

[[ 0  0  0 ...  0  0  0]
 [ 3  4  2 ...  1  3  1]
 [ 4  3  1 ...  2  2  2]
 ...
 [58 70 85 ... 95 80 60]
 [59 71 84 ... 94 81 59]
 [60 73 83 ... 95 80 60]]


In [7]:
#So here we can compare in Trial 1, after the 1st throw of dice what was the step position
#Accessing the last elements of 2d numpy array will give us the final step we are in 

In [8]:
final_steps = random_walk_transpose[-1]
print(final_steps)

[ 60  73  83  68  73 106  63  76  60  87  62  77  62  58  83  96  91 104
  69  74  50  60  89  86  98  46  48  71  99  61  71  57  70  52  89  74
  69  83  79  83  95  66  62  60  84  40  77 117  45  77  76  70  78  72
  76  54  79  95  72  74  85 103  97  82  93  77  54  95  67  66  90  62
  70  78  60 101  58  61  60  80  84  84  70  51  72  79  86  87  99  92
  49  81  88  63  72  52  84 101  82  79  58  64  68 101  74  91  44  85
  78  85  55  74  54  68  61  81  71 101  71 102 102  67  55 103  47  69
  78  87  83  73  78  87  57  62  70  58  90  62  87  68  82  80  71  72
  55  81  38  79  94  69  76  56 101  71  77  77  67  72  87  49  64  86
  88  65 102 118  97  92  69  63  45  69  48  95  85  71  72  84  82  76
  48  79  91  65  78  69  74  53  70  70  98  99  86  82  75  59  74  83
  80  65  97  52  61  86  64  87  95  66  54  63  95  89  72  63  84  61
  57  87  62 111  78  83  40  66  99  81  62  85  99  57  63  78  66  64
  68  86  50  57  72  71  85  90  72  88  76  68  5

In [9]:
len(final_steps[final_steps >= 60])/len(final_steps)

0.84